// Build script for @unitsml/unitsdb.
//
// Inputs (relative to repo root):
//   unitsdb-ruby/           — checked out at the released tag by CI
//   unitsdb-ruby/data/      — bundled YAML data files
//
// Outputs:
//   dist/unitsdb.js         — Opal-compiled bundle (Builder API)
//   dist/unitsdb-data.json  — bundled Database serialized as JSON
//   dist/index.js           — CJS façade (esbuild)
//   dist/index.mjs          — ESM façade (esbuild)
//   dist/index.d.ts         — TypeScript definitions (copied from src/)

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const esbuild = require("esbuild");

const ROOT = process.cwd();
const DIST = path.join(ROOT, "dist");
const RUBY_DIR = path.join(ROOT, "unitsdb-ruby");

function run(cmd, opts = {}) {
  console.log(`$ ${cmd}`);
  execSync(cmd, { stdio: "inherit", ...opts });
}

function ensureDist() {
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });
}

// Use Opal::Builder (Ruby API) — more reliable than the `opal` CLI
// for multi-gem builds. Mirrors the pattern unitsdb-ruby uses in its
// own Opal boot-file spec.
function compileOpal() {
  const script = `
    require "opal"
    require "opal/builder"
    require "rubygems"

    builder = Opal::Builder.new
    builder.append_paths("${RUBY_DIR}/lib")

    # Make every gem unitsdb-ruby depends on visible to Opal. Without
    # this, Opal::Builder::MissingRequire fires on `require "lutaml/model"`.
    %w[lutaml-model]..each do |g|
      spec = Gem::Specification.find_by_name(g)
      builder.append_paths(File.join(spec.gem_dir, "lib"))
    end

    builder.build("unitsdb/opal")
    File.write("${DIST}/unitsdb.js", builder.toString)
  `;
  execSync(`ruby -e '${script.replace(/\n\s*/g, "; ")}'`, {
    cwd: RUBY_DIR,
    stdio: "inherit",
    env: { ...process.env },
  });
  const size = fs.statSync(path.join(DIST, "unitsdb.js")).size;
  console.log(`wrote dist/unitsdb.js (${(size / 1024).toFixed(1)} KiB)`);
}

function dumpBundledData() {
  const script = `
    require "unitsdb"
    puts Unitsdb.database.to_json
  `;
  const json = execSync(`ruby -e '${script.replace(/\n\s*/g, "; ")}'`, {
    cwd: RUBY_DIR,
    encoding: "utf-8",
    env: { ...process.env },
  });
  fs.writeFileSync(path.join(DIST, "unitsdb-data.json"), json);
  console.log(`wrote dist/unitsdb-data.json (${(json.length / 1024).toFixed(1)} KiB)`);
}

function buildFacade() {
  const entry = path.join(ROOT, "src", "index.js");
  fs.writeFileSync(
    entry,
    `
// Generated by scripts/build.js — do not edit.
const fs = require("fs");
const path = require("path");

// Load the Opal bundle (registers Opal + Unitsdb on globalThis).
require("../dist/unitsdb.js");

const Unitsdb = globalThis.Opal.const_get("Unitsdb");
const Database = Unitsdb.const_get("Database");

function bundled() {
  const json = fs.readFileSync(path.join(__dirname, "..", "dist", "unitsdb-data.json"), "utf-8");
  return Database.from_json(json);
}

function fromJson(json) {
  return Database.from_json(json);
}

module.exports = { Unitsdb: { bundled, fromJson } };
`,
  );

  esbuild.buildSync({
    entryPoints: [entry],
    bundle: true,
    platform: "node",
    format: "cjs",
    outfile: path.join(DIST, "index.js"),
    loader: { ".json": "text" },
    define: { "process.env.NODE_ENV": '"production"' },
    target: "node16",
  });

  esbuild.buildSync({
    entryPoints: [entry],
    bundle: true,
    platform: "neutral",
    format: "esm",
    outfile: path.join(DIST, "index.mjs"),
    loader: { ".json": "text" },
    define: { "process.env.NODE_ENV": '"production"' },
    target: "es2020",
  });

  fs.copyFileSync(
    path.join(ROOT, "src", "index.d.ts"),
    path.join(DIST, "index.d.ts"),
  );

  console.log("wrote dist/index.{js,mjs,d.ts}");
}

function main() {
  const version = process.argv.find((a) => a.startsWith("--version="))?.split("=")[1];
  if (!version) {
    throw new Error("--version=X.Y.Z is required");
  }
  if (!fs.existsSync(RUBY_DIR)) {
    throw new Error(`expected unitsdb-ruby/ at ${RUBY_DIR}`);
  }

  ensureDist();
  compileOpal();
  dumpBundledData();
  buildFacade();

  const pkgPath = path.join(ROOT, "package.json");
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
  pkg.version = version;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
  console.log(`set package version to ${version}`);
}

main();
