// Build script for @unitsml/unitsdb.
//
// v1 strategy: ship the bundled Database as JSON (produced by the
// Ruby gem via `Database#to_json`) plus a small pure-JS façade that
// re-implements the high-level query methods. The Ruby gem remains
// the single source of truth for both data and reference behavior;
// the JS package re-expresses the read API in idiomatic JS.
//
// Why not Opal-compile the whole gem? Opal::Builder hangs on the
// lutaml-model dependency tree (unitsdb-ruby's own Opal spec stubs
// it for the same reason). A JSON dump + JS façade ships a much
// smaller bundle and runs natively in Node/browsers/deno without an
// embedded Ruby runtime.
//
// Inputs (relative to repo root):
//   unitsdb-ruby/           — checked out at the released tag by CI
//   unitsdb-ruby/data/      — bundled YAML data files
//
// Outputs:
//   dist/unitsdb-data.json  — bundled Database serialized as JSON
//   dist/index.js           — CJS façade (esbuild)
//   dist/index.mjs          — ESM façade (esbuild)
//   dist/index.d.ts         — TypeScript definitions (copied from src/)

const fs = require("fs");
const os = require("os");
const path = require("path");
const { execSync } = require("child_process");
const esbuild = require("esbuild");

const ROOT = process.cwd();
const DIST = path.join(ROOT, "dist");
const RUBY_DIR = path.join(ROOT, "unitsdb-ruby");

function ensureDist() {
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });
}

// Write `source` to a temp .rb file and run it under bundle exec.
// Ruby writes large outputs directly to disk (we pass paths in) so
// the multi-MB JSON dump never blocks on a pipe buffer.
function runBundleRuby(source) {
  const tmp = path.join(
    fs.mkdtempSync(path.join(os.tmpdir(), "unitsdb-js-")),
    "build.rb",
  );
  fs.writeFileSync(tmp, source);
  try {
    execSync(`bundle exec ruby ${tmp}`, {
      cwd: RUBY_DIR,
      stdio: "inherit",
      env: { ...process.env },
    });
  } finally {
    fs.rmSync(path.dirname(tmp), { recursive: true, force: true });
  }
}

// Dump the bundled Database as JSON. Ruby writes straight to the
// output file to avoid pipe-buffer deadlock.
function dumpBundledData() {
  const outPath = path.join(DIST, "unitsdb-data.json");
  const script = `
require "unitsdb"
File.write(${JSON.stringify(outPath)}, Unitsdb.database.to_json)
warn "wrote #{File.size(${JSON.stringify(outPath)})} bytes"
`;
  runBundleRuby(script);
  const size = fs.statSync(outPath).size;
  console.log(`wrote dist/unitsdb-data.json (${(size / 1024).toFixed(1)} KiB)`);
}

function buildFacade() {
  const dataPath = path.join(DIST, "unitsdb-data.json");
  const entry = path.join(ROOT, "src", "index.js");
  // Inline the JSON data at build time so the bundle has zero
  // runtime fs/path dependencies — works in browsers, deno, bun,
  // and node without adaptation.
  fs.writeFileSync(
    entry,
    [
      "// Generated by scripts/build.js — do not edit.",
      "import { Database } from './database';",
      "",
      "const DATA = " +
        fs.readFileSync(dataPath, "utf-8") +
        ";",
      "",
      "let cached = null;",
      "",
      "export function bundled() {",
      "  if (cached) return cached;",
      "  cached = new Database(DATA);",
      "  return cached;",
      "}",
      "",
      "export function fromJson(json) {",
      "  const data = typeof json === 'string' ? JSON.parse(json) : json;",
      "  return new Database(data);",
      "}",
      "",
      "export const Unitsdb = { bundled, fromJson };",
      "export default Unitsdb;",
      "",
    ].join("\n"),
  );

  // database.js ships as CJS today. Re-export it as ESM for the
  // façade entry.
  const dbSrc = path.join(ROOT, "src", "database.js");
  const dbEsm = path.join(ROOT, "src", "database.mjs");
  fs.copyFileSync(dbSrc, dbEsm);
  fs.writeFileSync(
    dbEsm,
    fs.readFileSync(dbEsm, "utf-8").replace(
      "module.exports = { Database, COLLECTIONS, SYMBOL_COLLECTIONS };",
      "export { Database, COLLECTIONS, SYMBOL_COLLECTIONS };",
    ),
  );
  fs.writeFileSync(
    entry,
    fs.readFileSync(entry, "utf-8").replace(
      "import { Database } from './database';",
      "import { Database } from './database.mjs';",
    ),
  );

  esbuild.buildSync({
    entryPoints: [entry],
    bundle: true,
    platform: "node",
    format: "cjs",
    outfile: path.join(DIST, "index.js"),
    define: { "process.env.NODE_ENV": '"production"' },
    target: "node16",
    minify: true,
  });

  esbuild.buildSync({
    entryPoints: [entry],
    bundle: true,
    platform: "neutral",
    format: "esm",
    outfile: path.join(DIST, "index.mjs"),
    define: { "process.env.NODE_ENV": '"production"' },
    target: "es2020",
    minify: true,
  });

  fs.copyFileSync(
    path.join(ROOT, "src", "index.d.ts"),
    path.join(DIST, "index.d.ts"),
  );

  console.log("wrote dist/index.{js,mjs,d.ts}");
}

function main() {
  const version = process.argv.find((a) => a.startsWith("--version="))?.split("=")[1];
  if (!version) {
    throw new Error("--version=X.Y.Z is required");
  }
  if (!fs.existsSync(RUBY_DIR)) {
    throw new Error(`expected unitsdb-ruby/ at ${RUBY_DIR}`);
  }

  ensureDist();
  dumpBundledData();
  buildFacade();

  const pkgPath = path.join(ROOT, "package.json");
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
  pkg.version = version;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
  console.log(`set package version to ${version}`);
}

main();
